import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const ADR_DIR = "docs/adr";
export const ADR_TEMPLATE_FILENAME = "0000-template.md";
export const ADR_REGISTRY_PATH = `${ADR_DIR}/README.md`;
export const ADR_INDEX_START = "<!-- adr-index:start — generated by `launchrail adr index`; edit the records, not this table -->";
export const ADR_INDEX_END = "<!-- adr-index:end -->";

export interface AdrEntry {
  /**
   * The handle other documents reference the record by: the four-digit number
   * of a legacy `NNNN-slug.md` record, the slug of a dated `YYYY-MM-DD-slug.md`
   * one. Ambiguous when two files share it.
   */
  id: string;
  /** Decision date of a dated record (`YYYY-MM-DD`); null for legacy numbered records. */
  date: string | null;
  /** Filename inside docs/adr/. */
  file: string;
  /** First `# ` heading (any `ADR-NNNN:` prefix stripped); the filename when there is none. */
  title: string;
  /** The `## Status` section's first paragraph, joined on one line; empty when the record has none. */
  status: string;
}

/** Legacy numbered records: `0031-adr-registry.md`. A dated filename is not a numbered one. */
const NUMBERED_FILENAME = /^(\d{4})-(?!\d{2}-\d{2}-)(.+)\.md$/;
/** Dated records: `2026-09-11-adr-date-slug-identifiers.md` — the date is when the decision was made. */
const DATED_FILENAME = /^(\d{4}-\d{2}-\d{2})-([a-z0-9][a-z0-9-]*)\.md$/;
const TITLE_PREFIX = /^ADR[-\s]?\d+\s*[:—–-]\s*/i;

function parseFilename(file: string): { id: string; date: string | null } | null {
  const dated = DATED_FILENAME.exec(file);
  if (dated?.[1] !== undefined && dated[2] !== undefined) return { id: dated[2], date: dated[1] };
  const numbered = NUMBERED_FILENAME.exec(file);
  if (numbered?.[1] !== undefined) return { id: numbered[1], date: null };
  return null;
}

function adrTitle(source: string, file: string): string {
  const heading = /^#\s+(.+)$/m.exec(source)?.[1];
  if (heading) return heading.replace(TITLE_PREFIX, "").trim();
  return file.replace(/\.md$/, "");
}

/** The first paragraph under `## Status`, whitespace-collapsed onto one line. */
function adrStatus(source: string): string {
  const match = /^##\s+Status[^\n]*\n([\s\S]*?)(?=^##\s|(?![\s\S]))/m.exec(source);
  if (!match) return "";
  const paragraph = (match[1] ?? "").trim().split(/\n\s*\n/)[0] ?? "";
  return paragraph.replace(/\s+/g, " ").trim();
}

/**
 * The decision records already in a repository's docs/adr/ (template and
 * registry excluded), sorted by filename — numbered records first, dated
 * records after them in date order, so the mixed corpus reads as a timeline.
 * Read-only.
 */
export function scanAdrs(cwd: string): AdrEntry[] {
  const dir = join(cwd, ADR_DIR);
  if (!existsSync(dir)) return [];
  const entries: AdrEntry[] = [];
  for (const file of readdirSync(dir).sort()) {
    if (file === ADR_TEMPLATE_FILENAME) continue;
    const parsed = parseFilename(file);
    if (!parsed) continue;
    let source = "";
    try {
      source = readFileSync(join(dir, file), "utf8");
    } catch {
      // Unreadable file — title falls back to the filename, status to empty.
    }
    entries.push({ ...parsed, file, title: adrTitle(source, file), status: adrStatus(source) });
  }
  return entries;
}

/** Ids (numbers or slugs) claimed by more than one record — every reference by id is ambiguous. */
export function duplicateAdrIds(entries: AdrEntry[]): string[] {
  const counts = new Map<string, number>();
  for (const entry of entries) counts.set(entry.id, (counts.get(entry.id) ?? 0) + 1);
  return [...counts.entries()].filter(([, n]) => n > 1).map(([id]) => id);
}

/** Records whose filename never appears in the registry — rows the index is missing. */
export function unindexedAdrs(registrySource: string, entries: AdrEntry[]): AdrEntry[] {
  return entries.filter((entry) => !registrySource.includes(entry.file));
}

// --- Relations -----------------------------------------------------------------

type Relation = "supersedes" | "amends" | "extends";
const FORWARD: Record<string, Relation> = { supersedes: "supersedes", amends: "amends", extends: "extends" };
const BACKWARD: Record<string, Relation> = {
  "superseded by": "supersedes",
  "amended by": "amends",
  "extended by": "extends",
};
const RELATION_KEYWORD = /\b(partially\s+superseded\s+by|superseded\s+by|amended\s+by|extended\s+by|supersedes|amends|extends)\b/gi;
/** A clause ends at the next relation keyword, a semicolon, or a sentence end. */
const CLAUSE_END = /;|\.\s|\.$/;

/** Every record the clause names: link targets that are record files, or `ADR-NNNN` mentions. */
function refsIn(clause: string, byFile: Map<string, AdrEntry>, byNumber: Map<string, AdrEntry>): AdrEntry[] {
  const refs: AdrEntry[] = [];
  const seen = new Set<string>();
  const push = (entry: AdrEntry | undefined) => {
    if (entry && !seen.has(entry.file)) {
      seen.add(entry.file);
      refs.push(entry);
    }
  };
  for (const match of clause.matchAll(/\]\(([^)\s]+)\)/g)) push(byFile.get((match[1] ?? "").split("/").pop() ?? ""));
  for (const match of clause.matchAll(/\bADR[-\s]?(\d{4})\b/g)) push(byNumber.get(match[1] ?? ""));
  return refs;
}

/**
 * The relation graph declared across the corpus. A record declares what it
 * `supersedes`/`amends`/`extends` in its own `## Status`; legacy records may also
 * carry the reverse (`amended by …`). Both directions feed one graph, keyed by
 * the earlier record's file, so the index can print back-references that no
 * record had to be edited to carry.
 */
export function adrRelations(entries: AdrEntry[]): Map<string, Record<Relation, AdrEntry[]>> {
  const byFile = new Map(entries.map((e) => [e.file, e]));
  const byNumber = new Map(entries.filter((e) => e.date === null).map((e) => [e.id, e]));
  const graph = new Map<string, Record<Relation, AdrEntry[]>>();
  const link = (target: AdrEntry, relation: Relation, source: AdrEntry) => {
    if (target.file === source.file) return;
    const slot = graph.get(target.file) ?? { supersedes: [], amends: [], extends: [] };
    if (!slot[relation].some((e) => e.file === source.file)) slot[relation].push(source);
    graph.set(target.file, slot);
  };

  for (const entry of entries) {
    const keywords = [...entry.status.matchAll(RELATION_KEYWORD)];
    keywords.forEach((match, i) => {
      const start = match.index + match[0].length;
      const rest = entry.status.slice(start, keywords[i + 1]?.index ?? entry.status.length);
      const end = CLAUSE_END.exec(rest);
      const clause = end ? rest.slice(0, end.index) : rest;
      const keyword = (match[1] ?? "").toLowerCase().replace(/\s+/g, " ").replace(/^partially /, "");
      const refs = refsIn(clause, byFile, byNumber);
      const forward = FORWARD[keyword];
      const backward = BACKWARD[keyword];
      if (forward) for (const target of refs) link(target, forward, entry);
      else if (backward) for (const source of refs) link(entry, backward, source);
    });
  }
  return graph;
}

// --- Index ---------------------------------------------------------------------

/** The leading word of the status line (`Accepted`, `Superseded`, …); Unclassified when there is no status at all. */
function stateOf(status: string): string {
  const word = /^([A-Za-z]+)/.exec(status)?.[1];
  if (!word) return "Unclassified";
  return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
}

function idLink(entry: AdrEntry): string {
  return `[${entry.id}](${entry.file})`;
}

/**
 * One record's status cell: its state, the relations it declares, and the
 * back-references derived from later records. Superseded records also name
 * their successor(s), the one fact a reader must not miss.
 */
export function adrStatusCell(entry: AdrEntry, entries: AdrEntry[], graph = adrRelations(entries)): string {
  const state = stateOf(entry.status);
  const declared = { supersedes: [] as AdrEntry[], amends: [] as AdrEntry[], extends: [] as AdrEntry[] };
  for (const [file, slot] of graph) {
    for (const relation of ["supersedes", "amends", "extends"] as const) {
      if (slot[relation].some((e) => e.file === entry.file)) {
        const target = entries.find((e) => e.file === file);
        if (target) declared[relation].push(target);
      }
    }
  }
  const received = graph.get(entry.file) ?? { supersedes: [], amends: [], extends: [] };
  const list = (records: AdrEntry[]) => records.map(idLink).join(", ");

  const parts: string[] = [];
  if (received.supersedes.length > 0 && state === "Superseded") parts.push(`**Superseded by ${list(received.supersedes)}**`);
  else if (received.supersedes.length > 0) parts.push(`${state} — partially superseded by ${list(received.supersedes)}`);
  else parts.push(state);
  if (declared.supersedes.length > 0) parts.push(`supersedes ${list(declared.supersedes)}`);
  if (declared.amends.length > 0) parts.push(`amends ${list(declared.amends)}`);
  if (declared.extends.length > 0) parts.push(`extends ${list(declared.extends)}`);
  if (received.amends.length > 0) parts.push(`amended by ${list(received.amends)}`);
  if (received.extends.length > 0) parts.push(`extended by ${list(received.extends)}`);
  return parts.join("; ");
}

/** The generated index table, markers included. */
export function adrIndexTable(entries: AdrEntry[]): string {
  const graph = adrRelations(entries);
  const header = "| ADR | Decided | Title | Status |\n| --- | --- | --- | --- |";
  const rows = entries.map(
    (e) => `| ${idLink(e)} | ${e.date ?? "—"} | ${e.title.replace(/\|/g, "\\|")} | ${adrStatusCell(e, entries, graph)} |`,
  );
  return [ADR_INDEX_START, header, ...rows, ADR_INDEX_END].join("\n");
}

/**
 * The registry with its index table regenerated in place. Between the markers
 * when they exist; otherwise the first table under `## Index` is replaced and
 * the markers introduced around it (a registry written before the generator
 * migrates on its first run). Null when the registry has neither.
 */
export function withRegeneratedIndex(registrySource: string, entries: AdrEntry[]): string | null {
  const table = adrIndexTable(entries);
  const start = registrySource.indexOf("<!-- adr-index:start");
  const end = registrySource.indexOf(ADR_INDEX_END);
  if (start !== -1 && end !== -1 && end > start) {
    return registrySource.slice(0, start) + table + registrySource.slice(end + ADR_INDEX_END.length);
  }
  const heading = /^##\s+Index\s*$/m.exec(registrySource);
  if (!heading) return null;
  const afterHeading = heading.index + heading[0].length;
  const rest = registrySource.slice(afterHeading);
  const tableMatch = /\n(\|[^\n]*\n)+/.exec(rest);
  if (!tableMatch) return null;
  const before = registrySource.slice(0, afterHeading + tableMatch.index);
  const after = rest.slice(tableMatch.index + tableMatch[0].length);
  return `${before}\n${table}\n${after}`;
}

/**
 * The seeded ADR registry. When init/sync adopts a repository that already has
 * decision records, the index prefills from them; a fresh repository gets the
 * empty index. Seeded once, then project-owned — but the table between the
 * markers is regenerated by `launchrail adr index`, so the project maintains
 * the records and the live picture, never the rows.
 */
export function adrRegistryContent(entries: AdrEntry[]): string {
  const unclassifiedNote =
    entries.some((e) => e.status === "")
      ? "\n\nRows marked **Unclassified** carry no `## Status` section yet. Classify each as you next touch its area: give the record a status line (`Accepted`, `Superseded by [id](file)`, …) and re-run `launchrail adr index`."
      : "";
  const livePicture =
    entries.length === 0
      ? "_No decisions recorded yet. When ADRs land, summarize here how they compose into the current system, and name the few a newcomer should read first._"
      : "_Not yet written. Summarize how the accepted decisions compose into the current system, and name the few ADRs a newcomer should read first._";

  return `# ADR registry

The index of every architecture decision record in this repository. Read this first, then open only the ADRs that touch the area you are working in — the index is the cheap surface; the records are depth.

An ADR records a decision and the context it was made in. It is **not documentation of the current system**: never treat an ADR as evidence that a component exists or still works as described — the code is the source of truth for what exists today.

## Index

${adrIndexTable(entries)}${unclassifiedNote}

## The live picture

How the accepted decisions compose into the current system. This section describes the present — rewrite it freely as the system grows; the ADRs behind it are history and stay untouched.

${livePicture}

## Maintaining this registry

- New ADRs copy [0000-template.md](0000-template.md) to \`YYYY-MM-DD-short-slug.md\` — the date the decision was made, then a slug unique in this directory. There is no sequence number to claim, so parallel branches never collide.
- The index table between the markers is **generated**: run \`launchrail adr index\` after adding or re-statusing a record (and after merging), and commit the result. Never hand-edit the rows; the rest of this file is yours.
- A new ADR declares what it supersedes, amends, or extends in its own \`## Status\` line, linking the earlier record by file. The index derives the reverse links, so amending an ADR does not require editing it. A superseded ADR's \`## Status\` line is still rewritten to name its successor — that is the one fact a reader of the record alone must not miss.
- Never delete or rename an ADR once it is referenced; superseded ADRs are historical records other documents link to.
`;
}
